# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-26 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preset',
            old_name='content',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='preset',
            old_name='title',
            new_name='name',
        ),
    ]
